Feat/76 metodo filtrado
ispp-2324-ocial/backend pull request #104
Opened 2024-04-03 10:13 UTC by carvarsou

- Añadido el método EventFiltered en views.py de event para poder filtrar eventos por categoría y fecha.

- Además, hemos vuelto a refactorizar el modelo de Event y las vistas de Create y Update ya que el atributo "description" se había cambiado de nuevo a "event" en la rama develop.

- El código del filtro se podría refactorizar para no tener un return por sentencia if.

CC @Domi-ATLAS

2024-04-03 10:19 UTC, carvarsou commented
Existen errores en los tests de varias entidades, sería necesario arreglarlos en otra rama que haga PR a develop, y así poder tener los tests correctos a partir de develop.

2024-04-04 10:22 UTC, adrrf requested changes
os dejo unos cuantos cambios

2024-04-04 10:22 UTC, adrrf commented on event/models.py
>      timeStart = models.DateTimeField(default="1030-01-01 09:00:00")
quidat el default da un error al ir al django admin

2024-04-04 10:22 UTC, adrrf commented on event/models.py
>      timeEnd = models.DateTimeField(default="1030-01-01 10:00:00")
idem

2024-04-04 10:22 UTC, adrrf commented on event/models.py
> +            self.description
Se cambia aqui pero tambien hay que cambiarlo en el __str__ en vez de event description

2024-04-04 10:22 UTC, adrrf commented on event/views.py
> +        if (category != None) and (timestart != None) and (timeend != None):
el filtro esta mal, esto te pilla que el tiempo de inicio sea EL MISMO que le doy como parámetro.

El filtro deberia darme los eventos que esten entre dichas fechas

2024-04-04 10:22 UTC, adrrf commented on event/views.py
> +        category = request.query_params.get("category")
además no tiene sentido filtrar por la fecha en la que acaba, yo pondria que la fecha de inicio este comprendida entre timestart y time end

2024-04-05 08:10 UTC, Domi-ATLAS commented on event/views.py
> +            200: OpenApiResponse(response=EventFilteredSerializer(many=True)),
Ya lo he cambiado en los ultimos commits

2024-04-05 08:11 UTC, Domi-ATLAS commented on event/models.py
>      timeStart = models.DateTimeField(default="1030-01-01 09:00:00")
Resuelto tambien

2024-04-05 08:11 UTC, Domi-ATLAS commented on event/models.py
> +            self.description
Cambiado en str

2024-04-05 08:12 UTC, Domi-ATLAS commented on event/views.py
> +        if (category != None) and (timestart != None) and (timeend != None):
Vale aqui tenemos un problema y es que si hacemos timeStart__gte => timestart, deja de detectar el gte, por el > o el <

2024-04-05 08:14 UTC, Domi-ATLAS commented on event/views.py
> +        category = request.query_params.get("category")
He cambiado el filtro, mira si ahora es como me comentas, ahora hay dos fechas de inicio, y el codigo coge los eventos entre el primer timeStart y el segundo timeStart, de forma que me da los eventos que tiene de valor en el timeStart uno que este comprendido entre los dos, incluyendo los valores, pero nunca escogera un evento con un timeStart fuera del rango.

2024-04-05 09:24 UTC, carvarsou commented on event/views.py
> +        category = request.query_params.get("category")
Un usuario normalmente quiere filtrar eventos por cuándo empiezan y/o cuándo terminan. Hacer este cambio de dos fechas de inicio no tiene tanto sentido y hace modificar la base del modelo de eventos.

2024-04-05 09:25 UTC, Domi-ATLAS commented on event/views.py
> +        category = request.query_params.get("category")
Ahora el filtro funciona, hemos mantenido comentado el anterior, por si se quiere pensar todavia, cual tendria mas sentido, ya que este segundo metodo es muy enrevesado

2024-04-05 14:06 UTC, adrrf commented on event/views.py
> +        category = request.query_params.get("category")
> Un usuario normalmente quiere filtrar eventos por cuándo empiezan y/o cuándo terminan. Hacer este cambio de dos fechas de inicio no tiene tanto sentido y hace modificar la base del modelo de eventos.

un usuario normalmente quiere saber que eventos hay en un lapso de tiempo. es decir imaginate que yo quiero saber que eventos hay la semana de feria, pues entonces pondría un filtro de 15/04 al 21/04 y el servidor estaria buscando los eventos que empiezan dichos dias. no le interesaria el evento que empieze el 15 y acabe el 21. ademas, no se requiere cambiar el modelo de datos.

2024-04-05 14:13 UTC, adrrf commented on event/views.py
> +        category = request.query_params.get("category")
cuando se filtra por las dos fechas
events = Event.objects.filter(timeStart__gte=timestart).filter(timeEnd__lte=timeend)
habria que poner
events = Event.objects.filter(timeStart__gte=timestart).filter(timeStart__lte=timeend)

habria que comprobar además que time start es posterior a time end y tirar un 400 si no
tambien comprobar si el evento esta dentro de las categorias que tenemos si no otro 400

2024-04-05 14:20 UTC, adrrf commented on event/views.py
> +        category = request.query_params.get("category")
@carvarsou @Domi-ATLAS

2024-04-06 09:48 UTC, Domi-ATLAS commented on event/views.py
> +        category = request.query_params.get("category")
Ya lo he implementado lo unico que hay codigo que se podria ahorrar refactorizando me he dado cuenta despues del push. Pero deberia ser funcional, a falta de comprobarse

2024-04-07 14:57 UTC, adrrf commented
ademas traedse los cambios de develop, para tener los test de user arreglados

2024-04-08 11:44 UTC, Domi-ATLAS commented on event/views.py
> +        if start != None and end != None and start > end:
cuando lo prove funcionaba bien y de la otra manera me saltaba error con la llamada de la variable que se hace en el createEvent por ejemplo

2024-04-08 11:45 UTC, Domi-ATLAS commented
los cambios de develop que lo haga alguien que sepa hacer rebase

2024-04-08 11:45 UTC, Domi-ATLAS commented
o ponerme los comandos del rebase aqui y lo hago esta tarde

2024-04-08 14:00 UTC, Domi-ATLAS commented
@adrrf mira si lo he hecho bien trayendome los cambios

2024-04-08 14:54 UTC, adrrf commented
aun no esta del todo hay que hacer el rebase desde el cliente de terminal
Step 1: Clone the repository or update your local repository with the latest changes.

git pull origin develop

Step 2: Switch to the base branch of the pull request.

git checkout  feat/76-metodo-filtrado

Step 3: Merge the head branch into the base branch.

git rebase develop

2024-04-08 17:17 UTC, Domi-ATLAS commented
que es el cluente del terminal?

2024-04-08 17:23 UTC, Domi-ATLAS commented
me salen cosas en consola y he reventado mi local al intentarlo

2024-04-09 11:20 UTC, adrrf commented
hay que solucionar un test cambiar el event string representation

2024-04-09 12:14 UTC, adrrf reviewed
todo en orden, buen trabajo

2024-04-09 12:15 UTC, adrrf approved these changes

2024-04-09 12:15 UTC, fravilpae approved these changes
Me funciona bien

2024-04-09 12:15 UTC, merged