fix: open api responses
ispp-2324-ocial/backend pull request #108
Opened 2024-04-05 15:55 UTC by adrrf

2024-04-06 09:51 UTC, Domi-ATLAS commented
No he visto ningún problema en el codigo, ya que son simples modificaciones, para mejora de la legibilidad y especificar ciertos mensajes, de la open API

2024-04-06 09:51 UTC, Domi-ATLAS approved these changes

2024-04-08 08:28 UTC, Jeszamgue requested changes
Los métodos EventGet, ClientGet, UsersGet y DjangoUserGet, deben devolver solo 1 objeto y no una lista, esto fue un fallo que tuvimos al hacer la definición de los métodos en semana santa por las prisas que había

2024-04-08 08:32 UTC, adrrf commented
@Jeszamgue estuve mirando para que en la definición de open api pusiera que solo devuelve un objeto, poniendo many=false y con otros medios, parece ser que automáticamente para los get, pone que devuelve una lista, no ocurre lo mismo con post etc por eso está así

2024-04-08 08:41 UTC, Jeszamgue commented
> @Jeszamgue estuve mirando para que en la definición de open api pusiera que solo devuelve un objeto, poniendo many=false y con otros medios, parece ser que automáticamente para los get, pone que devuelve una lista, no ocurre lo mismo con post etc por eso está así

Es por que tienen el generics.ListAPIView en la función en vez del APIView

2024-04-08 15:07 UTC, Jeszamgue approved these changes
Esta bien

2024-04-08 15:07 UTC, merged