Refactor/110 api
ispp-2324-ocial/backend pull request #116
Opened 2024-04-09 17:34 UTC by adrrf

cada commit es autoexplicativo

2024-04-09 17:54 UTC, carvarsou reviewed
Respecto al djangoUser, no estoy seguro si frontend necesita todos los atributos de la entidad, incluso datos sensibles como el password o is_staff. Creo que solo necesitan "username" y "email", adjunto captura por si @ferferga puede aclararlo mejor.

<img width="544" alt="image" src="https://github.com/ispp-2324-ocial/backend/assets/80246400/53486f64-1b9d-4ce4-aaad-0c5a396447f3">

Además, ese serializador de `ClientGetSerializer` no es el único en el que se devuelven datos del cliente. En los serializadores de todas las entidades donde aparezca ocialClient u ocialUser hay que añadirles los datos necesarios de djangoUser. De esta manera, se asegura la entidad única en frontend.

Respecto a los otros dos commits, en principio lo veo bien.

2024-04-10 11:44 UTC, ferferga requested changes
* Porque no se ha actualizado el EventSerializer en vez de crear un nuevo serializador? En frontend esto hace que tengamos que renombrar todos los tipos.
* Falta crear un serializador ``UserSerializer`` que aúne todos los tipos de usuario en uno, con las siguientes restricciones:
    * Si el usuario es el que ha hecho la solicitud, se devuelven todos los datos (username, email, suscripcion (enumerado), tipo, longitud, latidud, etc)
    * Si el usuario no es el actual, solo se debe mostrar su nombre y username, **ninguno de los otros datos expuestos actualmente** (como el de la ubicación).

Por completar la captura de Carlos, el UserSerializer deberia de tener estos campos:

- Si el serializador está serializando el usuario que ha iniciado la sesión actual:
    * last_login
    * username
    * first_name
    * last_name
    * email
    * date_joined
    * image
    * name
    * typeClient
    * defaultLatitude
    * defaultLongitude

- Si el serializador está serializando otro usuario:
    * username
    * first_name
    * last_name
    * date_joined
    * image
    * name
    * typeClient

2024-04-10 11:47 UTC, adrrf commented
el event serializer no se ha modificado pq el event details devuelve el campo like

2024-04-10 11:48 UTC, adrrf commented
lo del is client no se guarda en el login?

2024-04-10 11:49 UTC, ferferga commented
@adrrf Lee el edit que he hecho, me he confundido y ciertamente ese campo no existe

También, que diferencia hay entre *name*, *first_name*, *last_name*? @horgarler También tenía dudas sobre eso el otro día.

2024-04-10 11:55 UTC, adrrf commented
claro es el numero de likes, no la entidad

2024-04-10 11:56 UTC, adrrf commented
este es calculado cada vez que obtienes lis detalles

2024-04-10 12:54 UTC, adrrf commented
> * Porque no se ha actualizado el EventSerializer en vez de crear un nuevo serializador? En frontend esto hace que tengamos que renombrar todos los tipos.
> 
>     * Falta crear un serializador `UserSerializer` que aúne todos los tipos de usuario en uno, con las siguientes restricciones:
>       
>       * Si el usuario es el que ha hecho la solicitud, se devuelven todos los datos (username, email, suscripcion (enumerado), tipo, longitud, latidud, etc)
>       * Si el usuario no es el actual, solo se debe mostrar su nombre y username, **ninguno de los otros datos expuestos actualmente** (como el de la ubicación).
> 
> 
> Por completar la captura de Carlos, el UserSerializer deberia de tener estos campos:
> 
>     * Si el serializador está serializando el usuario que ha iniciado la sesión actual:
>       
>       * last_login
>       * username
>       * first_name
>       * last_name
>       * email
>       * date_joined
>       * image
>       * name
>       * typeClient
>       * defaultLatitude
>       * defaultLongitude
> 
>     * Si el serializador está serializando otro usuario:
>       
>       * username
>       * first_name
>       * last_name
>       * date_joined
>       * image
>       * name
>       * typeClient

el método que se pedia era el de obtener el cliente por los datos de sesión del cliente, modifico que se devuelvan los campos necesarios  del user serializer

2024-04-11 17:55 UTC, carvarsou commented
Se ha arreglado lo dicho en el punto 4: los datos de OcialClient no aparecen ya cuando estás creando como cliente un evento.
También a la hora de listar los eventos se muestran datos añadidos al OcialClient que pertenecen al DjangoUser, quedando así: 
>   * last_login
>   * username
>   * first_name
>   * last_name
>   * email
>   * date_joined
>   * image
>   * name
>   * typeClient
>   * defaultLatitude
>   * defaultLongitude

Quedaría pendiente poner la lógica en aquellas vistas que se accede a datos de otros clientes que se muestre de esta forma:

> * username
>  * first_name
>  * last_name
>  * date_joined
>  * image
>  * name
>  * typeClient

2024-04-13 10:58 UTC, carvarsou commented
Se ha añadido userSerializer como serializador único de los usuarios. Falta que las vistas utilicen correctamente y sin errores este nuevo serializador.

2024-04-14 10:25 UTC, carvarsou commented
Ya se han resuelto todos los conflictos con los métodos de swagger utilizando los nuevos serializadores de `EventSerializer` y `UserSerializer`.
Falta corregir los tests pero eso pertenece a una PR distinta.

2024-04-14 16:19 UTC, ferferga commented on event/views.py
> +                response=EventCreateSerializer(), description="El evento se ha actualizado"
Esto debería de ser el EventSerializer no?

```suggestion
                response=EventSerializer(), description="El evento se ha actualizado"
```

2024-04-14 16:19 UTC, ferferga commented on event/views.py
> +            return Response(serielized_event.data, status=status.HTTP_200_OK)
```suggestion
            serialized_event = EventSerializer(eventUpdate, context={ 'user': request.user })
            return Response(serialized_event.data, status=status.HTTP_200_OK)
```

2024-04-14 16:19 UTC, ferferga commented on event/views.py
> +            return Response(completed_data, status=status.HTTP_200_OK)
```suggestion
            serialized_event = EventSerializer(event, context={"user": request.user})
            return Response(serialized_event.data, status=status.HTTP_200_OK)
```

Por qué hace falta la copia?

2024-04-14 16:19 UTC, ferferga commented on payments/views.py
> +        # print(client_suscription)
```suggestion
```

2024-04-14 16:21 UTC, ferferga requested changes

2024-04-14 16:21 UTC, ferferga commented on event/serializers.py
> +            "likes": self.get_likes(instance),
```suggestion
    def to_representation(self, instance):
        event_data = {
            "creator": UserSerializer(instance.ocialClient, context={'user': self.context['user']}).data,
            "name": instance.name,
            "place": instance.place,
            "description": instance.description,
            "timeStart": instance.timeStart,
            "timeEnd": instance.timeEnd,
            "capacity": instance.capacity,
            "category": instance.category,
            "latitude": instance.latitude,
            "longitude": instance.longitude,
            "image": ImageSerializer(instance.image).data,
            "created_at": instance.created_at,
            "updated_at": instance.updated_at,
            "likes": instance.get_likes_count(),
```

Esto lo tienes que dejar así para que el OpenAPI se genere sin warnings

2024-04-14 16:22 UTC, adrrf commented on event/views.py
> +            return Response(serielized_event.data, status=status.HTTP_200_OK)
request.user no se debería usar, tenemos auth vía token hay que obtener el user por el token

2024-04-14 16:38 UTC, carvarsou commented on event/serializers.py
> +            "likes": self.get_likes(instance),
Hecho.

2024-04-14 16:38 UTC, carvarsou commented on payments/views.py
> +        # print(client_suscription)
Hecho.

2024-04-14 16:39 UTC, carvarsou commented on event/views.py
> +            return Response(completed_data, status=status.HTTP_200_OK)
Se coló, arreglado.

2024-04-14 16:40 UTC, carvarsou commented on event/views.py
> +            return Response(serielized_event.data, status=status.HTTP_200_OK)
Cambio los `request.user` que se hayan colado por `user` obtenido por token.

2024-04-14 16:40 UTC, carvarsou commented on event/views.py
> +                response=EventCreateSerializer(), description="El evento se ha actualizado"
Hecho.

2024-04-14 17:02 UTC, ferferga approved these changes

2024-04-14 23:31 UTC, merged