feat(locust_test): Implemented load tests
ispp-2324-ocial/backend pull request #129
Opened 2024-04-15 10:07 UTC by raumonmar1

Ya funcionan ambos test comienza a dar problemas cuando ponemos 1000 usuarios con ritmo de 100. Al hacer pull request saltará el warning de haber hecho cambios en el requirements.txt solo he incluido locust.

2024-04-15 10:28 UTC, raumonmar1 commented
@ispp-2324-ocial/backend da errores en test de usuario por lo que no deja mergear.

2024-04-20 17:32 UTC, adrrf commented
habria que poner las contraseñas parametrizadas en el env para que no salte el security breach

2024-04-20 17:32 UTC, adrrf requested changes
lo dicho en el comentario

2024-05-02 16:40 UTC, Domi-ATLAS approved these changes

2024-05-02 16:47 UTC, raumonmar1 reviewed
Ya está todo

2024-05-02 16:49 UTC, merged