PR/39 Solucion de colision de enumerados
ispp-2324-ocial/backend pull request #40
Opened 2024-03-05 20:47 UTC by Domi-ATLAS

2024-03-05 21:01 UTC, Jeszamgue approved these changes

2024-03-05 21:17 UTC, fravilpae approved these changes

2024-03-06 16:48 UTC, ferferga approved these changes

2024-03-06 23:24 UTC, ferferga requested changes

2024-03-06 23:24 UTC, ferferga commented on ocial/models.py
> +    LIVE_CONCERT = 4  # , ("Live concert")
Igual sería mejor ponerlo solo como texto en ambos lados (o igual a la izquierda numero a la derecha texto funciona mejor?)

Me acabo de dar cuenta de esto que me genera el cliente:
![image](https://github.com/ispp-2324-ocial/backend/assets/10274099/af21e5b2-4a97-4842-8f78-e74967a03559)

![image](https://github.com/ispp-2324-ocial/backend/assets/10274099/b78790d8-d161-4c00-b95d-c1e1da90a889)

2024-03-09 12:50 UTC, ferferga submitted a review, later dismissed
Con tus cambios funciona perfe el ``CategoryEnum``. Sin embargo, otro enum que ahora mismo está afectado por lo mismo es el de ``TypeClient`` (que no lo encuentro por ninguna parte en este PR, asi que supongo que hay que editar otros archivos, en swagger sale tmb).

2024-03-09 12:50 UTC, ferferga commented on ocial/models.py
> +    LIVE_CONCERT = "Live concert"  # , ("Live concert")
```suggestion
    SPORTS = "Sports"
    MUSIC = "Music"
    MARKETS = "Markets"
    RELAX_ACTIVITIES = "Relax activities"
    LIVE_CONCERT = "Live concert"
```

2024-03-09 12:50 UTC, ferferga commented on .github/workflows/openapi.yml
Este commit tmb habría que droppearlo

2024-03-11 08:09 UTC, adrrf commented on .github/workflows/openapi.yml
dropeado

2024-03-11 23:59 UTC, ferferga reviewed
@adrrf @Domi-ATLAS En lo que al cliente generado respecta, ya todo bien (al menos de momento). 

En mi opinión faltan por eliminar los comentarios que aún quedan en el ``CategoryEnum`` por ser redundantes y no aportar nada de información extra, pero eso ya lo dejo en vuestras manos.

2024-03-12 07:54 UTC, merged