Feat/42 feature social login
ispp-2324-ocial/backend pull request #47
Opened 2024-03-10 10:37 UTC by adrrf

Se ha implementado una primera versión de la autenticación de usuarios de ocial con google

2024-03-16 16:42 UTC, Jeszamgue requested changes

2024-03-16 16:42 UTC, Jeszamgue commented on user/serializers.py
> +        user_data = google.Google.validate(auth_token)
Esta línea esta duplicada

2024-03-19 12:31 UTC, fravilpae approved these changes
Funciona

2024-03-19 13:13 UTC, Jeszamgue approved these changes
Esta bien

2024-03-19 17:17 UTC, merged