feat(event): changed date and hour to timeStart and timeEnd
ispp-2324-ocial/backend pull request #52
Opened 2024-03-13 11:07 UTC by carvarsou

Cambiados los atributos de fecha y hora por un datetime de Inicio y otro de Fin para la entidad de Evento.

2024-03-13 11:07 UTC, Domi-ATLAS submitted a review, later dismissed

2024-03-14 08:06 UTC, adrrf requested changes
habria que comprobar en algun sitio ya sea modelo o vista que la fecha hora de inicio sea anterior a la de fin

2024-03-14 19:41 UTC, adrrf commented
@lDrakohh ocupate de la implementación de la comprobación, ya que @carvarsou y @Domi-ATLAS estan liados con front

2024-03-17 16:13 UTC, Domi-ATLAS commented
Ya he realizado los validadores para que los DateTimeFields, solo se puedan hacer en el futuro nunca en pasado y ademas que el inicio no sea mayor que el fin del evento

2024-03-24 09:29 UTC, Jeszamgue requested changes
La comprobación de las fechas en el swagger no funciona, tambien el date.time.today() me da error, se podria cambiar por el datetime.now poniendole la zona horaria de utc+1 sino.
Para la comprobación en vez de hacerlo en el save del models probad en el views del update y el create, asi: 
if data.get("timeStart") > data.get("timeEnd"):
            return Response(
                {"error": "Fecha invalida"},
                status=status.HTTP_400_BAD_REQUEST,
            )
pero para todas las comprobaciones

2024-03-24 09:31 UTC, Jeszamgue commented
@carvarsou @Domi-ATLAS

2024-03-24 17:02 UTC, Domi-ATLAS commented
Es el unico metodo que no funciona @Jeszamgue ? Pense lo del now pero no existe en Python 
por lo menos a mi no me sale

2024-03-24 17:47 UTC, Jeszamgue approved these changes
ya funciona bien

2024-03-24 17:51 UTC, fravilpae approved these changes

2024-03-26 11:40 UTC, adrrf submitted a review, later dismissed

2024-03-26 12:11 UTC, fravilpae approved these changes
Va perfectamente

2024-03-26 17:43 UTC, merged