feat/55 added image support to create event
ispp-2324-ocial/backend pull request #57
Opened 2024-03-19 19:07 UTC by adrrf

2024-03-20 18:04 UTC, adrrf commented
las imagenes se suben en base64 (https://www.base64-image.de/ para transformar) y para comprobar blurhash usar https://blurha.sh/ en el campo imagenB64 en los formularios de creacion de clientes y eventos y de edicion de eventos

2024-03-20 20:44 UTC, Jeszamgue requested changes
Esta bien, pero falta la dependencia del blurHash en el requirements.txt

2024-03-21 18:16 UTC, fravilpae approved these changes
Lo veo todo bien

2024-03-21 18:17 UTC, Jeszamgue approved these changes
Esta bien

2024-03-24 09:03 UTC, merged