feat(ratings): Migrado rating de event a user, corregido los modelos …
ispp-2324-ocial/backend pull request #62
Opened 2024-03-20 20:36 UTC by lDrakohh

…y los test de event ya funcionan

2024-03-20 20:37 UTC, lDrakohh commented
Test de event corregido
![a](https://i.gyazo.com/902ba972ec8a7aa22bc4edbbae83fdfe.png)

Los métodos de event siguen funcionando
![a](https://i.gyazo.com/b4d00520a365f192c6fc741529530fd3.png)

Creación del rating
![a](https://i.gyazo.com/c09e6af31ad612e8e9999d0eefcef3a7.png)

2024-03-21 18:08 UTC, adrrf approved these changes

2024-03-21 18:08 UTC, adrrf commented on user/views.py
> +
habria que comprobar que el usuario que crea el rating está logueado y que no es otro cliente y que no ha puesto ya una opinion sobre dicho cliente

2024-03-21 18:08 UTC, adrrf commented on user/views.py
> +class ClientIDListView(APIView):
esto para que es?

2024-03-21 18:09 UTC, adrrf requested changes
que he aprobado sin querer

2024-03-25 12:14 UTC, lDrakohh commented
Terminado el migrado de ratings. Se comprueba siempre que esté logueado, que solo puedan comentar usuarios de tipo OcialUser, que solo puedan tener un comentario por cliente, que funcionan correctamente los métodos delete, create y put

2024-03-26 11:23 UTC, adrrf requested changes

2024-03-26 11:23 UTC, adrrf commented on user/views.py
> +        user = request.user
hay que pillar el usuario por el token no por request.user

2024-03-26 11:23 UTC, adrrf commented on user/views.py
> +        user = request.user
idem

2024-03-26 11:23 UTC, adrrf commented on user/views.py
> +        user = request.user
idem

2024-03-26 18:58 UTC, lDrakohh commented
Arreglado

2024-03-27 09:40 UTC, fravilpae approved these changes
Funcionalmente, va todo bien. A la espera de si el cambio de usar el token está bien hecho

2024-03-28 09:13 UTC, merged