Feat/5 modelado de datos subscripciones
ispp-2324-ocial/backend pull request #63
Opened 2024-03-22 18:29 UTC by josecaog26

Se ha creado el modelo de datos de suscripciones.
Se ha implementado el CRUD de suscripciones

2024-03-23 15:35 UTC, adrrf requested changes

2024-03-23 15:35 UTC, adrrf commented on subscription/views.py
> +            )
esto permite crear varias suscrpciones por user, hay que verlo

2024-03-24 08:04 UTC, josecaog26 commented on subscription/views.py
> +            )
Si, ahora mismo no hay limite de suscripciones poer cliente, queria solucionarlo en la issue de validacion de suscripciones. O si lo veis mas oportuno lo soluciono en esta.

2024-03-24 09:38 UTC, fravilpae approved these changes

2024-03-24 09:55 UTC, fravilpae submitted a review, later dismissed
Funciona perfectamente.

Un cambio para mejorarlo es que no haya que indicarle todos los campos a la suscripción en el create y en el update, ya que se deberían rellenar automáticamente. Si se puede, mejoradlo para que solo haya que pasarle el tipo de suscripción, que todo lo demás ya se pilla automáticamente

2024-03-24 09:58 UTC, adrrf commented
> Funciona perfectamente.
> 
> Un cambio para mejorarlo es que no haya que indicarle todos los campos a la suscripción en el create y en el update, ya que se deberían rellenar automáticamente. Si se puede, mejoradlo para que solo haya que pasarle el tipo de suscripción, que todo lo demás ya se pilla automáticamente

a esto @josecaog26 yo en la issue https://github.com/ispp-2324-ocial/backend/issues/64 lo hago con los tokens y usuarios, se podria hacer asi igual

2024-03-24 10:02 UTC, adrrf requested changes
Hacer la obtencion del cliente por el token, como lo tengo en la issue 64

2024-03-24 17:11 UTC, adrrf requested changes
mirate como obtengo el usuario/cliente en el like y obten el cliente de la misma manera en la que yo obtengo el usuario en https://github.com/ispp-2324-ocial/backend/pull/66

2024-03-27 16:02 UTC, fravilpae commented
Esta PR se continua en #71

2024-03-28 02:20 UTC, closed without merging