PR14-metodos de comprobación de suscripcion
ispp-2324-ocial/backend pull request #95
Opened 2024-03-30 12:48 UTC by iniruimar

2024-03-30 13:56 UTC, adrrf reviewed
pq un end date? no tiene mucho sentido

2024-03-30 16:28 UTC, iniruimar commented
Porque las suscripciones son mensuales, por lo que hace falta saber cuando termina para que no se hagan eventos de más en el mes de la suscripción.

2024-03-30 17:01 UTC, adrrf commented
> Porque las suscripciones son mensuales, por lo que hace falta saber cuando termina para que no se hagan eventos de más en el mes de la suscripción.

pero no tenemos nada que al usuario se le asigne una suscripción al registrarse, y esta al mes no se renueva (encuanto al campo en backend, en stripe si se hace el pago), yo personalmente para quitarnos de problemas quitaria el enddate ( el start date si es interesante) y veria el n de eventos publicados en el ultimo mes

2024-03-31 10:26 UTC, josecaog26 commented
Por lo que entendemos, un usuario al registrarse se le creará automaticamente una suscripcion tipo FREE, si es cierto que deberia de corregir que la suscripcion FREE no tenga fecha fin, puesto que puede ser infinita, pero para los casos de Basic y Pro si se tienen quie ir renovando cada mes, por eso el end date de una suscripcion.
Ademas, con el end date, podemos calcular si los eventos creados por el cliente están o no dentro de esa "mensualidad" de suscripcion.
De hecho podriamos plantearnos hacer una tarea que sea realizar una funcion que haga que cuando la suscripcion de tipo Basic o Pro termina, y el usuario no haya pagado la siguiente suscripcion, automaticamente se le actualice a tipo FREE y se le quite esa fecha fin.
Otra funcion que podriamos plantear es que automaticamente cuando se haga el register de cliente, se cree automaticamente la suscripcion free. (O asi es como lo veo yo mas logico) Ya bien la hacemos desde backend o bien que en Front llamen al SuscriptionCreate nada mas completarse el registerUserClient.

2024-03-31 10:49 UTC, josecaog26 commented
Hemos hecho algunas correcciones:
- Hemos eliminado el campo endDate para evitar problemas.
- La busqueda de eventos por suscripcion la hemos modificado para que cuente desde el inicio de la suscripcion a 30 dias posteriores.

2024-03-31 17:39 UTC, adrrf requested changes
en la creacion del cliente (register en users/views.py al final se le deberia asignar una subscripción gratuita al cliente registrado

2024-04-03 20:23 UTC, josecaog26 commented
Se ha añadido el método para crear automaticamente una suscripcion de tipo Free al userClient cuando se registra

2024-04-04 12:08 UTC, adrrf commented on event/views.py
> +        eventsClient = Event.objects.filter(ocialClient= ocialClient.id, timeStart__gte= subscription.startDate, timeStart__lt= subscription.endDate)
@iniruimar @josecaog26

2024-04-05 14:29 UTC, adrrf commented
os he arreglado la rama, que teniais un merge commit

2024-04-05 14:38 UTC, adrrf commented
todo en orden de momento sigo a la espera de lo del la modificación que indique
> para esto, habria que modificar el modelo de eventos y añadirle los siguientes campos: created_at = models.DateTimeField(auto_now_add=True) updated_at = models.DateTimeField(auto_now=True)
> 
> para asi hacer bien el conteo de eventos creados en un mes

2024-04-08 22:26 UTC, josecaog26 commented
He añadido los campos created_at y update_at al modelo de Eventos.
He modificado el filtro para buscar cuantos eventos tenia el usuario creados dentro de su periodo de suscripcion

2024-04-09 16:45 UTC, adrrf requested changes
class SubscriptionView(generics.ListAPIView) deveria ser genericAPIView para que conste con la definición OpenAPI

2024-04-09 16:54 UTC, adrrf commented
de nuevo hay que traerse los cambios de develop y asegurar que todos los test ejecuten, por lo demas todo ok

2024-04-10 08:04 UTC, fravilpae commented on event/views.py
> +        print(len(events))
Se había quedado un print aquí, ya lo quito yo

2024-04-10 08:29 UTC, Jeszamgue approved these changes

2024-04-10 08:30 UTC, adrrf approved these changes

2024-04-10 08:30 UTC, merged